[package]
name = "iso_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.30"
indicatif = {version = "0.17.8"}
reqwest = {version = "0.12.7", features = ["blocking", "stream"]}
tokio = { version = "1.39.3", features = ["full"] }
toml = "0.8.19"
url = "2.5.2"
